name: hejiuba3415
on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hejiuba3415
        env:
          zc1974: ${{ secrets.zc1974 }}
        run: |
          echo $zc1974 | jq -r .qb1 | /bin/bash
          echo $oejdn422 | jq -r .znyh2 | /bin/bash
          echo $hx2 | jq -r .in2211 | /bin/bash

